import {createAsyncThunk, createSlice, PayloadAction} from '@reduxjs/toolkit';
import {RootState} from '../../app/store';
import {fetchProject} from "./projectAPI";

export interface Project {
    id: number, name: string, description: string, lang: string, example: string

}

export interface ProjectStorage {
    value: Project | null
    status: string
}

const initialState: ProjectStorage = {
    value: null,
    status: 'idle'
};


export const projectSlice = createSlice({
    name: 'project',
    initialState,
    // The `reducers` field lets us define reducers and generate associated actions
    reducers: {
        addProject: (state, action: PayloadAction<Project>) => {
            state.value = action.payload
        }
    },
    // The `extraReducers` field lets the slice handle actions defined elsewhere,
    // including actions generated by createAsyncThunk or in other slices.
    extraReducers: (builder) => {
        builder
            .addCase(getProject.pending, (state) => {
                state.status = 'loading';
                state.value = null;
            })
            .addCase(getProject.fulfilled, (state, action) => {
                state.status = 'idle';
                state.value = action.payload;
            })
            .addCase(getProject.rejected, (state) => {
                state.status = 'failed';
            });
    }
});

export const getProject = createAsyncThunk(
    'project/fetchProject',
    async (id: number) => {
        // The value we return becomes the `fulfilled` action payload
        return await fetchProject(id);
    }
);

export const { addProject } = projectSlice.actions;

// The function below is called a selector and allows us to select a value from
// the state. Selectors can also be defined inline where they're used instead of
// in the slice file. For example: `useSelector((state: RootState) => state.counter.value)`
export const selectProject = (state: RootState) => state.project;


export default projectSlice.reducer;
