import {createAsyncThunk, createSlice, PayloadAction} from '@reduxjs/toolkit';
import {RootState} from '../../app/store';
import {fetchProjects} from "./projectsAPI";
import {Project, Projects} from "../../app/interfaces";


const initialState: Projects = {
    value: [],
    status: 'idle'
};


export const projectsSlice = createSlice({
    name: 'projects',
    initialState,
    // The `reducers` field lets us define reducers and generate associated actions
    reducers: {
        addProject: (state, action: PayloadAction<Project>) => {
            state.value = [...state.value, action.payload]
        }
    },
    // The `extraReducers` field lets the slice handle actions defined elsewhere,
    // including actions generated by createAsyncThunk or in other slices.
    extraReducers: (builder) => {
        builder
            .addCase(getProjects.pending, (state) => {
                state.status = 'loading';
            })
            .addCase(getProjects.fulfilled, (state, action) => {
                state.status = 'idle';
                state.value = action.payload;
            })
            .addCase(getProjects.rejected, (state) => {
                state.status = 'failed';
            });
    }
});

export const getProjects = createAsyncThunk(
    'pages/fetchPages',
    async () => {
        // The value we return becomes the `fulfilled` action payload
        return await fetchProjects();
    }
);

export const { addProject } = projectsSlice.actions;

// The function below is called a selector and allows us to select a value from
// the state. Selectors can also be defined inline where they're used instead of
// in the slice file. For example: `useSelector((state: RootState) => state.counter.value)`
export const selectProjects = (state: RootState) => state.projects;


export default projectsSlice.reducer;
